language: python
python:
- 2.7
- 3.5

sudo: false

notifications:
  email:
  - wolf@physik.uni-bonn.de
  
install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
     wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - conda install --yes numpy scipy pyyaml matplotlib nose jupyter pandas 
  - conda info -a
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - python setup.py develop

script: nosetests
